# Generated by Django 4.2.3 on 2023-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_maspix", "0002_remove_blog_date_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Website", "Website"),
                    ("Desain", "Desain"),
                    ("Machine Learning", "Machine Learning"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
